### ISSUE TITLE
How to make snapshot testing of withStyles

### ISSUE THREAD

**Issue by telored** [kriasoft/isomorphic-style-loader#115]
when i try to make snapshot testing of some component that uses withStyles i get the following error:

TypeError: Cannot read property 'apply' of undefined

      at WithStyles.componentWillMount (node_modules/isomorphic-style-loader/lib/withStyles.js:71:64)
      at node_modules/react-test-renderer/lib/ReactCompositeComponent.js:345:23
      at measureLifeCyclePerf (node_modules/react-test-renderer/lib/ReactCompositeComponent.js:73:12)
      at ReactCompositeComponentWrapper.performInitialMount (node_modules/react-test-renderer/lib/ReactCompositeComponent.js:344:9)
      at ReactCompositeComponentWrapper.mountComponent (node_modules/react-test-renderer/lib/ReactCompositeComponent.js:255:21)
      at Object.mountComponent (node_modules/react-test-renderer/lib/ReactReconciler.js:43:35)
      at ReactCompositeComponentWrapper.performInitialMount (node_modules/react-test-renderer/lib/ReactCompositeComponent.js:368:34)
      at ReactCompositeComponentWrapper.mountComponent (node_modules/react-test-renderer/lib/ReactCompositeComponent.js:255:21)
      at Object.mountComponent (node_modules/react-test-renderer/lib/ReactReconciler.js:43:35)
      at mountComponentIntoNode (node_modules/react-test-renderer/lib/ReactTestMount.js:53:31)
      at ReactTestReconcileTransaction.perform (node_modules/react-test-renderer/lib/Transaction.js:141:20)
      at batchedMountComponentIntoNode (node_modules/react-test-renderer/lib/ReactTestMount.js:67:27)
      at ReactDefaultBatchingStrategyTransaction.perform (node_modules/react-test-renderer/lib/Transaction.js:141:20)
      at Object.batchedUpdates (node_modules/react-test-renderer/lib/ReactDefaultBatchingStrategy.js:60:26)
      at Object.batchedUpdates (node_modules/react-test-renderer/lib/ReactUpdates.js:95:27)
      at Object.render [as create] (node_modules/react-test-renderer/lib/ReactTestMount.js:126:18)
      at Object.it (src/routes/error/ErrorPage.test.js:11:37)
          at new Promise (<anonymous>)
      at Promise.resolve.then.el (node_modules/p-map/index.js:46:16)
          at <anonymous>
      at process._tickCallback (internal/process/next_tick.js:188:7)

my test file:

import React from 'react';
import renderer from 'react-test-renderer';
import Page from './Page';

jest.fn('isomorphic-style-loader/lib/withStyles', () => {
    console.log('nothing');
});

describe('Testing<Page />', () => {
  it('Snapshot test', () => {
    const tree = renderer.create(
      <Page />,
    );
    expect(tree).toMatchSnapshot();
  });
});

**Comment by frenzzy** [comment]
You may create a [TestProvider](https://github.com/kriasoft/isomorphic-style-loader/blob/master/test/withStyles.spec.js#L28-L45) which may render styles to include them into snapshot too.

**Comment by maksimgm** [comment]
@frenzzy Can you show a code example of how to do this?
